//! Deterministic reference-documentation generator (`atelier --emit-docs <dir>`).
//!
//! This is the anti-drift engine (PRD F6, ADR-003/001): the reference pages in the docs
//! site are *derived from the binary*, never hand-maintained, so they cannot diverge from
//! the source of truth. It reads three in-process surfaces — the redacted merged config
//! ([`build_printable_config`]), the CLI surface ([`Cli::command`]), and the slash catalog
//! ([`slash_commands::catalog`]) — and writes Markdown fragments whose `{title, nav_order}`
//! frontmatter matches the `docs` content-collection schema (task_03).
//!
//! Mirrors `src/codemap` (an entry fn + file writers + Markdown-by-`format!`). Output is
//! **deterministic**: stable ordering (the `Printable*` projection and the catalog are both
//! ordered), no timestamps, and no live-runtime / doctor probes.

use crate::config::{build_printable_config, EffectiveConfig};
use crate::slash_commands::{catalog, SlashCommandKind};
use crate::Cli;
use anyhow::{Context, Result};
use clap::CommandFactory;
use std::fs;
use std::path::{Path, PathBuf};

const CONFIGURATION_FILE: &str = "configuration.md";
const CLI_FILE: &str = "cli.md";

/// `nav_order` for the generated Configuration page (after the hand-written prose pages).
const CONFIGURATION_NAV_ORDER: u32 = 30;
/// `nav_order` for the generated CLI & Commands page.
const CLI_NAV_ORDER: u32 = 40;

/// Result of an [`emit_docs`] run: the Markdown fragments written, for the CLI summary and
/// tests. Mirrors `codemap::CodemapSummary`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DocgenSummary {
    /// Generated Markdown fragments, in write order.
    pub written: Vec<PathBuf>,
}

/// Emits the deterministic Markdown reference fragments into `out_dir`, creating it if
/// needed. Reads only in-process surfaces (config / clap / slash catalog); never probes the
/// live environment, so two runs over the same config are byte-identical.
pub fn emit_docs(config: &EffectiveConfig, out_dir: &Path) -> Result<DocgenSummary> {
    fs::create_dir_all(out_dir)
        .with_context(|| format!("failed to create docs output dir {}", out_dir.display()))?;

    let mut written = Vec::new();

    let configuration = render_configuration(config)?;
    let configuration_path = out_dir.join(CONFIGURATION_FILE);
    fs::write(&configuration_path, configuration.as_bytes())
        .with_context(|| format!("failed to write {}", configuration_path.display()))?;
    written.push(configuration_path);

    let cli = render_cli_and_commands();
    let cli_path = out_dir.join(CLI_FILE);
    fs::write(&cli_path, cli.as_bytes())
        .with_context(|| format!("failed to write {}", cli_path.display()))?;
    written.push(cli_path);

    Ok(DocgenSummary { written })
}

/// One-line-per-file summary of what was emitted, mirroring `codemap::render_summary`.
pub fn render_summary(summary: &DocgenSummary) -> String {
    let mut output = format!("emit-docs: wrote {} fragment(s)\n", summary.written.len());
    for path in &summary.written {
        output.push_str(&format!("- {}\n", path.display()));
    }
    output
}

fn frontmatter(title: &str, nav_order: u32) -> String {
    // Quote the title so values with YAML-significant characters (e.g. the `&` in
    // "CLI & Commands") parse as plain strings under the docs collection's zod schema.
    format!("---\ntitle: \"{title}\"\nnav_order: {nav_order}\n---\n\n")
}

/// Renders the Configuration reference from the redacted [`build_printable_config`]
/// projection. The full effective config is shown once as a canonical TOML block (identical
/// to `--print-config`, so it cannot drift), followed by one section per top-level
/// `atelier.toml` table — each heading carries the literal `[section]` token so the
/// coverage test can assert every section is documented.
fn render_configuration(config: &EffectiveConfig) -> Result<String> {
    let printable = build_printable_config(config);
    let effective_toml = toml::to_string_pretty(&printable)
        .context("failed to render effective configuration as TOML")?;

    let mut out = frontmatter("Configuration", CONFIGURATION_NAV_ORDER);
    out.push_str("# Configuration\n\n");
    out.push_str(
        "Generated by `atelier --emit-docs` from the merged, redacted effective \
configuration — this reference is derived from the binary and cannot drift from the \
source of truth. Secrets are never emitted: API keys appear only as the *name* of the \
environment variable that supplies them, and prompt bodies are reduced to a \
`prompt_source` label. `[presets.*]` is documented separately because it is materialized \
only by the `--init-config` starter template, not by the merged config.\n\n",
    );

    out.push_str("## Effective configuration\n\n");
    out.push_str("The complete redacted config, byte-identical to `atelier --print-config`:\n\n");
    out.push_str("```toml\n");
    out.push_str(&effective_toml);
    if !effective_toml.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("```\n\n");

    out.push_str("## Sections\n\n");
    out.push_str(&render_config_section(
        "Workspace",
        "[workspace]",
        "Read/write roots and workspace policy that bound every filesystem action.",
    ));
    out.push_str(&render_config_section(
        "Features",
        "[features]",
        "Opt-in feature flags (for example, `parallel_step_groups`, `governance_early_abort`).",
    ));
    out.push_str(&render_config_section(
        "Approval",
        "[approval]",
        "Approval-system posture — the gray-area `floor` (`warn` / `enforce`) that governs \
in-between actions.",
    ));
    out.push_str(&render_config_section(
        "UI",
        "[ui]",
        "Terminal UI preferences (for example, `hide_banner`).",
    ));
    out.push_str(&render_config_section(
        "Keybindings",
        "[keybindings]",
        "The effective key map, shown as `[keybindings.<context>]` → `action = \"key\"`. \
Honored only from user-scope config (home or `--config`); a project-local config's \
`[keybindings]` is ignored. Set an action to `false` to unbind it.",
    ));
    out.push_str(&render_config_section(
        "Limits",
        "[limits]",
        "Run guardrails such as the maximum number of parallel agent steps.",
    ));
    out.push_str(&render_config_section(
        "Council",
        "[council]",
        "The serial review workflow: default preset, timeout, execution mode, and the \
review-member presets.",
    ));
    out.push_str(&render_config_section(
        "Runtimes",
        "[runtimes]",
        "Runtime definitions (`codex`, `claude`, `cursor`, `http_api`, `fake`), each \
keyed as `[runtimes.<name>]` in the block above.",
    ));
    out.push_str(&render_config_section(
        "Agents",
        "[agents]",
        "Agent profiles — runtime, model and fallback chain, effort, capabilities, tools, \
and prompt source — each keyed as `[agents.<name>]` in the block above.",
    ));

    Ok(out)
}

fn render_config_section(name: &str, token: &str, description: &str) -> String {
    format!("### {name} — `{token}`\n\n{description}\n\n")
}

/// Renders the CLI & Commands reference: every `atelier` long flag walked from
/// [`Cli::command`], then every slash command from [`slash_commands::catalog`]. Both
/// iterators are stable, so the output is deterministic.
fn render_cli_and_commands() -> String {
    let mut out = frontmatter("CLI & Commands", CLI_NAV_ORDER);
    out.push_str("# CLI & Commands\n\n");
    out.push_str(
        "Generated by `atelier --emit-docs` from the `atelier` binary's argument parser and \
the slash-command catalog — every flag and command below is read directly from the \
source of truth.\n\n",
    );

    out.push_str("## Command-line flags\n\n");
    out.push_str("Invoke as `atelier [FLAGS]`.\n\n");
    out.push_str("| Flag | Value | Description |\n");
    out.push_str("| --- | --- | --- |\n");
    let command = Cli::command();
    for arg in command.get_arguments() {
        let Some(long) = arg.get_long() else {
            continue;
        };
        // Boolean/count flags report a default value name (the upcased arg id) even though
        // they take no value — only show the value column for args that actually consume one.
        let value = if arg.get_action().takes_values() {
            arg.get_value_names()
                .map(|names| {
                    names
                        .iter()
                        .map(|name| format!("`<{name}>`"))
                        .collect::<Vec<_>>()
                        .join(" ")
                })
                .unwrap_or_default()
        } else {
            String::new()
        };
        let description = arg
            .get_help()
            .map(|help| help.to_string().replace('\n', " "))
            .unwrap_or_default();
        out.push_str(&format!(
            "| `--{long}` | {} | {} |\n",
            escape_table_cell(&value),
            escape_table_cell(&description)
        ));
    }

    out.push_str("\n## Slash commands\n\n");
    out.push_str(
        "Available inside the TUI composer. \"Handled by\" indicates which surface owns \
execution.\n\n",
    );
    out.push_str("| Command | Usage | Description | Handled by |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for spec in catalog() {
        let handled_by = match spec.kind {
            SlashCommandKind::TuiLocal => "TUI",
            SlashCommandKind::AppCommand => "app",
            SlashCommandKind::PromptPrefix => "prompt prefix",
        };
        out.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            escape_table_cell(spec.label),
            escape_table_cell(spec.usage),
            escape_table_cell(spec.description),
            handled_by
        ));
    }

    out
}

/// Escapes a value for inclusion in a Markdown table cell. Pipes (`|`) would otherwise be
/// read as column separators — `/goal | /goal <text>` is a real catalog usage string.
fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{load_effective_config, ConfigLoadOptions};
    use tempfile::tempdir;

    fn default_config() -> EffectiveConfig {
        let dir = tempdir().unwrap();
        let config_path = dir.path().join("empty-home.toml");
        fs::write(&config_path, "schema_version = 1\n").unwrap();
        load_effective_config(ConfigLoadOptions {
            working_directory: dir.path().to_path_buf(),
            config_path: Some(config_path),
        })
        .unwrap()
    }

    fn parse_frontmatter(markdown: &str) -> (String, u32) {
        let body = markdown
            .strip_prefix("---\n")
            .expect("fragment must start with frontmatter fence");
        let end = body.find("\n---\n").expect("frontmatter must be closed");
        let front = &body[..end];
        let mut title = None;
        let mut nav_order = None;
        for line in front.lines() {
            if let Some(rest) = line.strip_prefix("title: ") {
                title = Some(rest.trim_matches('"').to_string());
            } else if let Some(rest) = line.strip_prefix("nav_order: ") {
                nav_order = Some(rest.parse::<u32>().expect("nav_order must be a number"));
            }
        }
        (
            title.expect("title required"),
            nav_order.expect("nav_order required"),
        )
    }

    #[test]
    fn configuration_contains_every_config_section_header() {
        let config = default_config();
        let markdown = render_configuration(&config).unwrap();
        for section in [
            "[agents]",
            "[runtimes]",
            "[council]",
            "[limits]",
            "[ui]",
            "[keybindings]",
            "[approval]",
            "[features]",
            "[workspace]",
        ] {
            assert!(
                markdown.contains(section),
                "configuration reference missing section header {section}"
            );
        }
    }

    #[test]
    fn cli_reference_contains_every_long_flag() {
        let markdown = render_cli_and_commands();
        let command = Cli::command();
        for arg in command.get_arguments() {
            let Some(long) = arg.get_long() else {
                continue;
            };
            let flag = format!("--{long}");
            assert!(
                markdown.contains(&flag),
                "CLI reference missing long flag {flag}"
            );
        }
    }

    #[test]
    fn commands_reference_contains_every_slash_command() {
        let markdown = render_cli_and_commands();
        for spec in catalog() {
            assert!(
                markdown.contains(spec.label),
                "commands reference missing slash command {}",
                spec.label
            );
        }
    }

    #[test]
    fn fragments_begin_with_valid_collection_frontmatter() {
        let config = default_config();
        let (config_title, config_nav) = parse_frontmatter(&render_configuration(&config).unwrap());
        assert_eq!(config_title, "Configuration");
        assert_eq!(config_nav, CONFIGURATION_NAV_ORDER);

        let (cli_title, cli_nav) = parse_frontmatter(&render_cli_and_commands());
        assert_eq!(cli_title, "CLI & Commands");
        assert_eq!(cli_nav, CLI_NAV_ORDER);
    }

    #[test]
    fn emit_docs_is_deterministic_and_free_of_runtime_probes() {
        let config = default_config();
        let first_dir = tempdir().unwrap();
        let second_dir = tempdir().unwrap();

        let first = emit_docs(&config, first_dir.path()).unwrap();
        let second = emit_docs(&config, second_dir.path()).unwrap();

        assert_eq!(first.written.len(), 2);
        assert_eq!(second.written.len(), 2);

        for (a, b) in first.written.iter().zip(&second.written) {
            let a_bytes = fs::read(a).unwrap();
            let b_bytes = fs::read(b).unwrap();
            // Byte-identical across runs proves there are no timestamps or other
            // run-varying (live-runtime) values in the output.
            assert_eq!(
                a_bytes,
                b_bytes,
                "fragment {} differs between runs",
                a.file_name().unwrap().to_string_lossy()
            );
        }

        // The Configuration fragment is built purely from the redacted config projection —
        // doctor's live probe output (e.g. version detection) must never leak into it.
        // (`cli.md` legitimately documents the `--doctor` flag, so it is exempt.)
        let configuration = render_configuration(&config).unwrap().to_lowercase();
        for forbidden in ["doctor", "detected", "checking runtime"] {
            assert!(
                !configuration.contains(forbidden),
                "configuration reference contains live-runtime text {forbidden:?}"
            );
        }
    }

    #[test]
    fn emit_docs_writes_both_fragments() {
        let config = default_config();
        let dir = tempdir().unwrap();
        let summary = emit_docs(&config, dir.path()).unwrap();
        assert!(dir.path().join(CONFIGURATION_FILE).exists());
        assert!(dir.path().join(CLI_FILE).exists());
        assert_eq!(summary.written.len(), 2);
    }
}
