pub mod actions;
pub mod app;
pub mod cli;
pub mod codemap;
pub mod config;
pub mod diagnostics;
pub mod docgen;
pub mod doctor;
pub mod file_index;
pub mod governance;
pub mod history;
pub mod ids;
pub mod keybindings;
pub mod orchestrator;
pub mod runtime;
pub mod skills;
pub mod slash_commands;
pub mod tui;
pub mod util;

pub use cli::{run_cli, Cli};
